apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-jmatos-test
  labels:
    app: microservicio-jmatos-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-jmatos-test
  template:
    metadata:
      labels:
        app: microservicio-jmatos-test
        version: v1
    spec:
      containers: 
      - name: microservicio-jmatos-test
        image: jesusmatosp/microservicio-jmatos-test:1.0.3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-jmatos-test
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: microservicio-jmatos-test